# Generated by Django 4.2.3 on 2023-07-22 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 22, 19, 11, 53, 988838)),
            preserve_default=False,
        ),
    ]
